// <auto-generated>
// Generated from audio/audio_play_tags_master.proto
// Target: Client
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Client.MasterData
{
    [MemoryTable("AudioPlayTagsMaster"), MessagePackObject(true)]
    public sealed partial class AudioPlayTagsMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        public int AudioId { get; set; }

        [SecondaryKey(0), NonUnique]
        public int AudioPlayTag { get; set; }
    }
}
