// <auto-generated>
// Generated from audio/audio_master.proto
// Target: Client
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Client.MasterData
{
    [MemoryTable("AudioMaster"), MessagePackObject(true)]
    public sealed partial class AudioMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        public string Name { get; set; }

        public string AssetName { get; set; }

        public string Desc { get; set; }

        [SecondaryKey(0), NonUnique]
        public int AudioCategory { get; set; }
    }
}
