// <auto-generated>
// Generated from score_time_attack/score_time_attack_stage_item_master.proto
// Target: Client
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Client.MasterData
{
    [MemoryTable("ScoreTimeAttackStageItemMaster"), MessagePackObject(true)]
    public sealed partial class ScoreTimeAttackStageItemMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        public string Name { get; set; }

        [SecondaryKey(0)]
        public string AssetName { get; set; }

        public int Point { get; set; }
    }
}
