// <auto-generated>
// Generated from score_time_attack/score_time_attack_stage_item_spawn_master.proto
// Target: Client
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Client.MasterData
{
    [MemoryTable("ScoreTimeAttackStageItemSpawnMaster"), MessagePackObject(true)]
    public sealed partial class ScoreTimeAttackStageItemSpawnMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        [SecondaryKey(0), NonUnique]
        public int StageId { get; set; }

        public int GroupId { get; set; }

        public int StageItemId { get; set; }

        public int X { get; set; }

        public int Y { get; set; }

        public int Z { get; set; }

        public int MinSpawnCount { get; set; }

        public int MaxSpawnCount { get; set; }
    }
}
