// <auto-generated>
// Generated from score_time_attack/score_time_attack_stage_master.proto
// Target: Client
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Client.MasterData
{
    [MemoryTable("ScoreTimeAttackStageMaster"), MessagePackObject(true)]
    public sealed partial class ScoreTimeAttackStageMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        [SecondaryKey(0), NonUnique]
        public int GroupId { get; set; }

        public int Order { get; set; }

        public string Name { get; set; }

        public string AssetName { get; set; }

        public int TotalTime { get; set; }

        public int MaxPoint { get; set; }

        public int? PlayerId { get; set; }

        public int? NextStageId { get; set; }
    }
}
