// <auto-generated>
// Generated from survivor/survivor_item_drop_master.proto
// Target: Client
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Client.MasterData
{
    [MemoryTable("SurvivorItemDropMaster"), MessagePackObject(true)]
    public sealed partial class SurvivorItemDropMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        [SecondaryKey(0), NonUnique]
        public int GroupId { get; set; }

        public int ItemId { get; set; }

        public int DropRate { get; set; }
    }
}
