// <auto-generated>
// Generated from survivor/survivor_player_master.proto
// Target: Client
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Client.MasterData
{
    [MemoryTable("SurvivorPlayerMaster"), MessagePackObject(true)]
    public sealed partial class SurvivorPlayerMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        public string Name { get; set; }

        public string AssetName { get; set; }

        public int StartingWeaponId { get; set; }
    }
}
