// <auto-generated>
// Generated from survivor/survivor_player_level_master.proto
// Target: Client
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Client.MasterData
{
    [MemoryTable("SurvivorPlayerLevelMaster"), MessagePackObject(true)]
    public sealed partial class SurvivorPlayerLevelMaster
    {
        [PrimaryKey(0)]
        public int PlayerId { get; set; }

        [PrimaryKey(1)]
        public int Level { get; set; }

        public int RequiredExp { get; set; }

        public int MaxHp { get; set; }

        public int MaxStamina { get; set; }

        public int StaminaDepleteRate { get; set; }

        public int StaminaRegenRate { get; set; }

        public int MoveSpeed { get; set; }

        public int RunSpeed { get; set; }

        public int PickupRange { get; set; }

        public int CritRate { get; set; }

        public int CritDamage { get; set; }

        public int InvincibilityDuration { get; set; }

        public int ItemAttractDistance { get; set; }

        public int ItemAttractSpeed { get; set; }

        public int ItemCollectDistance { get; set; }

        public int DamageBonus { get; set; }

        public int WeaponChoiceCount { get; set; }
    }
}
