// <auto-generated>
// Generated from survivor/survivor_stage_wave_enemy_master.proto
// Target: Client
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Client.MasterData
{
    [MemoryTable("SurvivorStageWaveEnemyMaster"), MessagePackObject(true)]
    public sealed partial class SurvivorStageWaveEnemyMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        [SecondaryKey(0), NonUnique]
        public int WaveId { get; set; }

        public int EnemyId { get; set; }

        public int SpawnCount { get; set; }

        public int SpawnInterval { get; set; }

        public int SpawnDelay { get; set; }

        public int MinSpawnDistance { get; set; }

        public int MaxSpawnDistance { get; set; }

        public int ItemDropGroupId { get; set; }

        public int ExpDropGroupId { get; set; }
    }
}
