using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Game.Shared.Scriptable.Database;
using UnityEditor;
using UnityEngine;

namespace Game.Shared.Scriptable.Database.EditorTools
{
    /// <summary>
    /// [Table] 付きマスターデータクラスを走査し、二次/複合キーの型付きファインダを持つ
    /// 部分テーブルクラス（{型名}Table.g.cs）を生成するエディタツール。
    /// </summary>
    public static class ScriptableTableGenerator
    {
        private const string OutDir = "Assets/Programs/Runtime/Shared/Scriptable/Database/Generated";

        [MenuItem("Tools/Scriptable Database/Generate")]
        public static void Generate()
        {
            Directory.CreateDirectory(OutDir);
            int n = 0;
            foreach (var type in TableTypes())
            {
                File.WriteAllText($"{OutDir}/{type.Name}Table.g.cs", Emit(type));
                n++;
            }
            AssetDatabase.Refresh();
            Debug.Log($"[TableGenerator] {n} table(s) generated.");
        }

        private static IEnumerable<Type> TableTypes() =>
            AppDomain.CurrentDomain.GetAssemblies()
                .SelectMany(SafeTypes)
                .Where(t => t.IsClass && t.GetCustomAttribute<ScriptableTableAttribute>() != null);

        private static IEnumerable<Type> SafeTypes(Assembly a)
        {
            try { return a.GetTypes(); }
            catch (ReflectionTypeLoadException e) { return e.Types.Where(x => x != null); }
        }

        private static (string name, Type type) NameType(MemberInfo m) =>
            m is FieldInfo f ? (f.Name, f.FieldType) : (m.Name, ((PropertyInfo)m).PropertyType);

        private sealed class Col
        {
            public string Name;
            public Type Type;
            public int Order;
            public bool NonUnique;
        }

        private static string Emit(Type type)
        {
            var members = type.GetMembers(BindingFlags.Public | BindingFlags.Instance)
                .Where(m => m is FieldInfo || (m is PropertyInfo p && p.CanRead))
                .ToList();

            var (pkName, pkType) = NameType(members.First(m => m.GetCustomAttribute<PrimaryKeyAttribute>() != null));
            string pkT = TypeName(pkType);

            var indices = new SortedDictionary<int, List<Col>>();
            foreach (var m in members)
            {
                var (name, memberType) = NameType(m);
                foreach (var sk in m.GetCustomAttributes<SecondaryKeyAttribute>())
                {
                    if (!indices.TryGetValue(sk.IndexNo, out var list)) indices[sk.IndexNo] = list = new List<Col>();
                    list.Add(new Col { Name = name, Type = memberType, Order = sk.KeyOrder, NonUnique = sk.NonUnique });
                }
            }

            string table = type.Name + "Table";
            string ns = type.Namespace;
            string menu = type.GetCustomAttribute<ScriptableTableAttribute>().Name ?? type.Name;

            string i0 = ns != null ? "    " : "";   // クラスのインデント
            string i1 = i0 + "    ";                 // メンバのインデント
            string i2 = i1 + "    ";                 // メソッド本体のインデント

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated />");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using Game.Shared.Scriptable.Database;");
            sb.AppendLine();
            if (ns != null)
            {
                sb.AppendLine($"namespace {ns}");
                sb.AppendLine("{");
            }
            sb.AppendLine($"{i0}[CreateAssetMenu(menuName = \"{menu}\")]");
            sb.AppendLine($"{i0}public sealed partial class {table} : ScriptableTable<{type.Name}>");
            sb.AppendLine($"{i0}{{");

            // PrimaryKey: records 自体が主キー昇順のソート済みインデックス（OnValidate で整列）。
            sb.AppendLine($"{i1}// PrimaryKey: {pkName}");
            sb.AppendLine($"{i1}private static readonly System.Func<{type.Name}, {pkT}> _pkSel = r => r.{pkName};");
            sb.AppendLine($"{i1}private static readonly IComparer<{pkT}> _pkCmp = Comparer<{pkT}>.Default;");
            EmitMethod(sb, i1, i2, type.Name, $"FindBy{pkName}", $"{pkT} key",
                $"FindUnique(records, key, _pkSel, _pkCmp)");
            EmitMethod(sb, i1, i2, "bool", $"TryFindBy{pkName}", $"{pkT} key, out {type.Name} record",
                $"TryFindUnique(records, key, _pkSel, _pkCmp, out record)");
            EmitMethod(sb, i1, i2, type.Name, $"FindClosestBy{pkName}", $"{pkT} key, bool lower = true",
                $"FindClosest(records, key, _pkSel, _pkCmp, lower)");
            EmitMethod(sb, i1, i2, $"ScriptableTableRecords<{type.Name}>", $"FindRangeBy{pkName}", $"{pkT} min, {pkT} max, bool asc = true",
                $"FindRange(records, min, max, _pkSel, _pkCmp, asc)");

            foreach (var kv in indices)
            {
                var cols = kv.Value.OrderBy(c => c.Order).ToList();
                bool many = cols.Any(c => c.NonUnique);
                string keyT = cols.Count == 1
                    ? TypeName(cols[0].Type)
                    : "(" + string.Join(", ", cols.Select(c => TypeName(c.Type))) + ")";
                string sel = cols.Count == 1
                    ? $"r => r.{cols[0].Name}"
                    : "r => (" + string.Join(", ", cols.Select(c => "r." + c.Name)) + ")";
                string s = string.Join("And", cols.Select(c => c.Name));
                string selF = $"_sel{kv.Key}";   // セレクタ（静的・無キャプチャ）
                string cmpF = $"_cmp{kv.Key}";   // コンパレータ（静的）
                string idxF = $"_idx{kv.Key}";   // インデックス配列キャッシュ（インスタンス）
                string idxP = $"Idx{kv.Key}";

                sb.AppendLine();
                sb.AppendLine($"{i1}// SecondaryKey index {kv.Key}: {string.Join(", ", cols.Select(c => c.Name))}");
                sb.AppendLine($"{i1}private static readonly System.Func<{type.Name}, {keyT}> {selF} = {sel};");
                sb.AppendLine($"{i1}private static readonly IComparer<{keyT}> {cmpF} = Comparer<{keyT}>.Default;");
                sb.AppendLine($"{i1}private {type.Name}[] {idxF};");
                sb.AppendLine($"{i1}private {type.Name}[] {idxP} => {idxF} ??= BuildSortedIndex(records, {selF}, {cmpF});");

                if (many)
                {
                    EmitMethod(sb, i1, i2, $"ScriptableTableRecords<{type.Name}>", $"FindBy{s}", $"{keyT} key",
                        $"FindMany({idxP}, {selF}, {cmpF}, key)");
                    EmitMethod(sb, i1, i2, $"ScriptableTableRecords<{type.Name}>", $"FindRangeBy{s}", $"{keyT} min, {keyT} max, bool asc = true",
                        $"FindRange({idxP}, min, max, {selF}, {cmpF}, asc)");
                    EmitMethod(sb, i1, i2, $"ScriptableTableRecords<{type.Name}>", $"FindClosestBy{s}", $"{keyT} key, bool lower = true",
                        $"FindManyClosest({idxP}, key, {selF}, {cmpF}, lower)");
                }
                else
                {
                    EmitMethod(sb, i1, i2, type.Name, $"FindBy{s}", $"{keyT} key",
                        $"FindUnique({idxP}, key, {selF}, {cmpF})");
                    EmitMethod(sb, i1, i2, "bool", $"TryFindBy{s}", $"{keyT} key, out {type.Name} record",
                        $"TryFindUnique({idxP}, key, {selF}, {cmpF}, out record)");
                }
            }

            sb.AppendLine();
            sb.AppendLine("#if UNITY_EDITOR");
            sb.AppendLine($"{i1}[ContextMenu(\"Sort & Validate\")]");
            sb.AppendLine($"{i1}public override void EditorSortAndValidate()");
            sb.AppendLine($"{i1}{{");
            sb.AppendLine($"{i2}SortAndValidate(_pkSel, _pkCmp);");
            foreach (var k in indices.Keys) sb.AppendLine($"{i2}_idx{k} = null;");
            sb.AppendLine($"{i1}}}");
            sb.AppendLine();
            sb.AppendLine($"{i1}public override bool EditorIsSorted() => IsSortedByKey(_pkSel, _pkCmp);");
            sb.AppendLine("#endif");
            sb.AppendLine($"{i0}}}");
            if (ns != null) sb.AppendLine("}");
            return sb.ToString();
        }

        // 1 メソッドをブロック本体（複数行）で出力する。可読性のため式本体の 1 行化は避ける。
        private static void EmitMethod(StringBuilder sb, string i1, string i2, string ret, string name, string args, string body)
        {
            sb.AppendLine();
            sb.AppendLine($"{i1}public {ret} {name}({args})");
            sb.AppendLine($"{i1}{{");
            sb.AppendLine($"{i2}return {body};");
            sb.AppendLine($"{i1}}}");
        }

        private static readonly Dictionary<Type, string> Builtin = new Dictionary<Type, string>
        {
            { typeof(int), "int" }, { typeof(long), "long" }, { typeof(short), "short" }, { typeof(byte), "byte" },
            { typeof(bool), "bool" }, { typeof(float), "float" }, { typeof(double), "double" },
            { typeof(string), "string" }, { typeof(char), "char" },
        };

        private static string TypeName(Type t) =>
            Builtin.TryGetValue(t, out var s) ? s : "global::" + t.FullName.Replace('+', '.');
    }
}
