// <auto-generated>
// Generated from score_time_attack/score_time_attack_enemy_spawn_master.proto
// Target: Server
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Server.MasterData
{
    [MemoryTable("ScoreTimeAttackEnemySpawnMaster"), MessagePackObject(true)]
    public sealed partial class ScoreTimeAttackEnemySpawnMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        [SecondaryKey(0), NonUnique]
        public int StageId { get; set; }

        public int GroupId { get; set; }

        public int EnemyId { get; set; }

        public int X { get; set; }

        public int Y { get; set; }

        public int Z { get; set; }

        public int MinSpawnCount { get; set; }

        public int MaxSpawnCount { get; set; }
    }
}
