// <auto-generated>
// Generated from survivor/survivor_weapon_master.proto
// Target: Server
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Server.MasterData
{
    [MemoryTable("SurvivorWeaponMaster"), MessagePackObject(true)]
    public sealed partial class SurvivorWeaponMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        [SecondaryKey(0), NonUnique]
        public int WeaponType { get; set; }

        public int Rarity { get; set; }

        public string Name { get; set; }

        public string IconAssetName { get; set; }

        public string Description { get; set; }

        public string HitEffectAssetName { get; set; }

        public int HitEffectScale { get; set; }
    }
}
