// <auto-generated>
// Generated from survivor/survivor_stage_wave_master.proto
// Target: Server
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Server.MasterData
{
    [MemoryTable("SurvivorStageWaveMaster"), MessagePackObject(true)]
    public sealed partial class SurvivorStageWaveMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        [SecondaryKey(0), NonUnique]
        public int StageId { get; set; }

        public int WaveNumber { get; set; }

        public int StartTime { get; set; }

        public int Duration { get; set; }

        public int EnemySpeedMultiplier { get; set; }

        public int EnemyHealthMultiplier { get; set; }

        public int EnemyDamageMultiplier { get; set; }

        public int ExperienceMultiplier { get; set; }

        public int TargetKillCount { get; set; }

        public int RequiredBossKills { get; set; }

        public int ScoreMultiplier { get; set; }
    }
}
