// <auto-generated>
// Generated from survivor/survivor_weapon_level_master.proto
// Target: Server
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Server.MasterData
{
    [MemoryTable("SurvivorWeaponLevelMaster"), MessagePackObject(true)]
    public sealed partial class SurvivorWeaponLevelMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        [SecondaryKey(0), NonUnique]
        [SecondaryKey(1, keyOrder: 0)]
        public int WeaponId { get; set; }

        [SecondaryKey(1, keyOrder: 1)]
        public int Level { get; set; }

        public string AssetName { get; set; }

        public string Description { get; set; }

        public int Damage { get; set; }

        public int Range { get; set; }

        public int Speed { get; set; }

        public int Duration { get; set; }

        public int Cooldown { get; set; }

        public int ProcRate { get; set; }

        public int ProcInterval { get; set; }

        public int EmitCount { get; set; }

        public int EmitDelay { get; set; }

        public int EmitLimit { get; set; }

        public int HitCount { get; set; }

        public int HitBoxRate { get; set; }

        public int CritHitRate { get; set; }

        public int CritHitMultiplier { get; set; }

        public int Knockback { get; set; }

        public int Vacuum { get; set; }

        public int Spin { get; set; }

        public int Penetration { get; set; }

        public int Bounce { get; set; }

        public int Chain { get; set; }

        public int Homing { get; set; }

        public int Spread { get; set; }
    }
}
