// <auto-generated>
// Generated from survivor/survivor_enemy_master.proto
// Target: Server
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Server.MasterData
{
    [MemoryTable("SurvivorEnemyMaster"), MessagePackObject(true)]
    public sealed partial class SurvivorEnemyMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        public string Name { get; set; }

        public string AssetName { get; set; }

        [SecondaryKey(0), NonUnique]
        public int EnemyType { get; set; }

        public int BaseHp { get; set; }

        public int BaseDamage { get; set; }

        public int MoveSpeed { get; set; }

        public int AttackRange { get; set; }

        public int AttackCooldown { get; set; }

        public int HitStunDuration { get; set; }

        public int RotationSpeed { get; set; }

        public int DeathAnimDuration { get; set; }

        public int ExperienceValue { get; set; }

        public int? DropItemId { get; set; }

        public int DropRate { get; set; }

        public int MaxConcurrent { get; set; }

        public int SpawnRadius { get; set; }

        public int AttackRangeExitMultiplier { get; set; }
    }
}
