// <auto-generated>
// Generated from survivor/survivor_item_master.proto
// Target: Server
// </auto-generated>
using MasterMemory;
using MessagePack;

namespace Game.Server.MasterData
{
    [MemoryTable("SurvivorItemMaster"), MessagePackObject(true)]
    public sealed partial class SurvivorItemMaster
    {
        [PrimaryKey]
        public int Id { get; set; }

        public string Name { get; set; }

        public string AssetName { get; set; }

        [SecondaryKey(0), NonUnique]
        public int ItemType { get; set; }

        public int EffectValue { get; set; }

        public int EffectRange { get; set; }

        public int EffectDuration { get; set; }

        public int Rarity { get; set; }

        public int Scale { get; set; }
    }
}
